# Generated by Django 4.2.26 on 2025-11-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasil_prediksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilprediksi',
            name='lokasi_knn_farrel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hasilprediksi',
            name='lokasi_knn_thariq',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hasilprediksi',
            name='lokasi_naive_bayes',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hasilprediksi',
            name='lokasi_neural_network',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hasilprediksi',
            name='lokasi_random_forest',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hasilprediksi',
            name='lokasi_svm',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hasilprediksi',
            name='persentase_model_knn_farrel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hasilprediksi',
            name='persentase_model_knn_thariq',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hasilprediksi',
            name='persentase_model_naive_bayes',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hasilprediksi',
            name='persentase_model_neural_network',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hasilprediksi',
            name='lokasi',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hasilprediksi',
            name='persentase_model_Random_Forest',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hasilprediksi',
            name='persentase_model_SVM',
            field=models.CharField(default='', max_length=50),
        ),
    ]
