# Generated by Django 4.2.26 on 2025-12-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasil_prediksi', '0002_hasilprediksi_lokasi_knn_farrel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilprediksi',
            name='persentase_lokasi_tidak_ditemukan',
            field=models.CharField(default='', max_length=50),
        ),
    ]
