# Generated by Django 4.2.26 on 2025-11-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithPickle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('svm_model', models.BinaryField()),
                ('rf_model', models.BinaryField()),
                ('knn_thariq_model', models.BinaryField()),
                ('naive_bayes_model', models.BinaryField()),
                ('knn_farrel_model', models.BinaryField()),
                ('neural_network_model', models.BinaryField()),
            ],
        ),
    ]
