# Generated by Django 4.2.26 on 2025-12-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwithpickle',
            name='akurasi_knn_farrel',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modelwithpickle',
            name='akurasi_knn_thariq',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modelwithpickle',
            name='akurasi_naive_bayes',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modelwithpickle',
            name='akurasi_neural_network',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modelwithpickle',
            name='akurasi_rf',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='modelwithpickle',
            name='akurasi_svm',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
